# VacationPy
----

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
from pprint import pprint

# Import API key
from config import g_key

### Store WeatherPy csv results in DataFrame

In [2]:
#Upload city_weather.csv into new DataFrame 
cities_file = pd.read_csv("city_weather_data.csv")
cities_df = pd.DataFrame(cities_file)
cities_df.rename(columns={"Unnamed: 0":"Index"},inplace=True)
cities_df.set_index("Index", inplace=True)
cities_df.head(10)

,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed
Index,,,,,,,,,
0,Avarua,4,CK,1580319106,94,-21.21,-159.78,75.20,11.25
1,Jalu,0,LY,1580319229,38,29.03,21.55,60.17,4.00
2,Pevek,100,RU,1580319229,98,69.70,170.31,-18.18,10.20
3,Kruisfontein,87,ZA,1580319230,83,-34.00,24.73,64.35,9.44
4,Ribeira Grande,75,PT,1580319230,93,38.52,-28.70,62.60,11.41
5,Bluff,66,NZ,1580319230,69,-46.60,168.33,53.01,3.00
6,Srednekolymsk,6,RU,1580319230,83,67.45,153.68,-27.62,5.68
7,Mataura,3,NZ,1580319230,69,-46.19,168.86,53.01,3.00
8,Hermanus,47,ZA,1580319230,69,-34.42,19.23,68.00,8.01
9,Albany,40,US,1580319023,50,42.60,-73.97,35.01,5.82

### Humidity Heatmap
* Latitude and Longitude act as locations and Humidity as the weight (density of the heatmap).
* Add Heatmap layer to map.

In [4]:
gmaps.configure(api_key=g_key)
# Store 'Lat' and 'Lng' into  locations 
locations = cities_df[["Latitude", "Longitude"]].astype(float)

In [6]:
# Heatmap layer
# Please note that the map will likely not show in GitHub's markdown when Jupyter Notebook is uploaded.
# A map.png has been saved to view heatmap
humidity = cities_df["Humidity"]

figure_layout = {
    'width': '1000px',
    'height': '600px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}

fig = gmaps.figure(layout=figure_layout)

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 2)
fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(border='1px solid black', height='600px', margin='0 auto 0 auto', padding='1px', wiâ€¦

! [heatmap] (map.jpg)

### DataFrame with ideal weather criteria

In [31]:
#Narrowed down to find ideal weather condition
#Max temperature higher than 80 but lower than 95
#Windspeed less than 10mph
#Cloudiness less than 20
#Humidity less than 80
hotel_df = cities_df.loc[(cities_df["Max Temp"] > 80) & (cities_df["Max Temp"] < 95) & (cities_df["Wind Speed"] < 10)
                           & (cities_df["Cloudiness"] < 20) & (cities_df["Humidity"] < 80)]

In [33]:
#output to show remaining items after narrowing down.
hotel_df.head()

,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed
Index,,,,,,,,,
84,Kulhudhuffushi,0,MV,1580268879,65,6.62,73.07,81.84,9.93
87,Mount Gambier,0,AU,1580268646,17,-37.83,140.77,89.60,9.17
431,U Thong,15,TH,1580268900,56,14.38,99.89,81.84,2.91
457,Amahai,17,ID,1580268966,70,-3.33,128.92,85.82,9.13
564,Angoram,0,PG,1580268988,54,-4.06,144.07,91.80,4.97